#!/usr/bin/env python3

import json

# Read the roms.json file
with open("roms.json", "r") as file:
    data = json.load(file)

# Sort the data lexicographically by the name key
sorted_data = sorted(data, key=lambda x: x["name"])

# Write the content to a markdown file
with open("roms.md", "w") as output_file:
    # Write the header
    output_file.write(
        """---
layout: page
title: ROMS list
permalink: /roms/
---

## List of ROMs available

You can find the full list in the JSON file [here](http://roms.sidecart.xyz/roms.json).

"""
    )

    # Write the sorted list of ROMs
    for item in sorted_data:
        rom_name = item["name"]
        rom_description = item["description"]
        rom_size = item["size_kb"]
        rom_url = item["url"]

        output_file.write(
            f"- **{rom_name}**\n  - *Description*: {rom_description}\n  - *Size*: {rom_size} KB\n  - [Link to ROM]({rom_url})\n\n"
        )

print("Markdown file 'roms.md' has been created successfully.")
