#!/usr/bin/env python3

import json

# Read the roms.json file
with open("roms.json", "r") as file:
    data = json.load(file)

# Sort the data alphabetically ignoring case by the name key
sorted_data = sorted(data, key=lambda x: x["name"].lower())

# Write the content to a markdown file
with open("roms.md", "w") as output_file:
    # Write the header
    output_file.write(
        """---
layout: basic
title: ROMS list
permalink: /roms/
date: 2024-06-01T00:00:00Z
meta_description: "List of available ROMs for Atari ST computers"

---

## List of ROMs available

You can find the full list in the JSON file [here](http://roms.sidecartridge.com/roms.json).

| Name | Description | Size (KB) |
| --- | --- | --- |
"""
    )

    for item in sorted_data:
        rom_name = f"[{item['name']}]({item['url']})"
        rom_description = item["description"]
        rom_size = item["size_kb"]

        output_file.write(f"| {rom_name} | {rom_description} | {rom_size} |\n")

print("Markdown file 'roms.md' has been created successfully.")
